name: Build and Upload to PyPI

on:
  push:
    branches:
      - main

jobs:

  build-linux:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel Cython
        python -m pip install twine
  
    - name: Build Linux wheels
      run: python setup.py bdist_wheel
  
    - name: Upload Linux wheels to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: python -m twine upload --non-interactive --skip-existing dist/*

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Build Windows wheels
      run: |
        python -m pip install --upgrade pip setuptools wheel Cython
        python setup.py bdist_wheel

    - name: Upload Windows wheels to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install twine
        python -m twine upload --non-interactive --skip-existing dist/*

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Build macOS wheels
      run: |
        python -m pip install --upgrade pip setuptools wheel Cython
        python setup.py bdist_wheel
    
    - name: Upload macOS wheels to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install twine
        python -m twine upload --non-interactive --skip-existing dist/*