name: Build and Publish to PyPI

on:
  push:
    branches: 
      - main  # Assuming your main branch is called 'main'; change it to 'master' if your main branch has a different name.
  pull_request:  # This will run on pull requests for testing, but won't publish to PyPI.

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Use the Python version relevant to your project.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython setuptools wheel

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        CIBW_BEFORE_BUILD: "pip install Cython"

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl

  publish:
    needs: build_wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}