name: Build and Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install cython
          pip install pyinstaller  # or replace with cx_Freeze if preferred

      - name: Build binary distribution
        run: |
          pyinstaller --onefile miksi_ai_sdk/__init__.py  # Assuming __init__.py is the entry point of your package

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          distributions: "dist/*"
          skip_existing: true
