name: Build, Upload, and Publish

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          before_build: python -m pip install Cython auditwheel

      - name: Upload wheels to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@unstable/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: ./wheelhouse
