name: Build wheels

on:
  push:

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - name: Build wheels
        uses: ./.cibuildwheel/action.yml

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist