name: Build and Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools Cython

      - name: Build and package
        run: |
          python setup.py sdist
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash -c "pip install wheel setuptools Cython && /io/build-linux-wheels.sh"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload --repository pypi dist/*
