name: Build and Publish to PyPI

on:
  push:
    branches: 
      - main  # Adjust if your main development branch has a different name.
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust according to your project requirements.

      - name: Install Cython and other build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          pip install setuptools wheel

      - name: Build Wheels with cibuildwheel
        uses: pypa/cibuildwheel@2.16.2
        with:
          output-dir: 'wheelhouse'
        env:
          CIBW_BEFORE_BUILD: pip install Cython

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  publish:
    needs: build_wheels
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure this matches the version used in the build job.

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}