name: Build and Publish to PyPI

on:
  workflow_dispatch: # Enables manual triggering of this workflow

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        include:
          # Define combinations explicitly
          - os: ubuntu-latest
            python-version: '3.7'
            platform: linux
          - os: macos-latest
            python-version: '3.8'
            platform: macos
          - os: windows-latest
            python-version: '3.9'
            platform: windows
        exclude:
          - os: macos-latest
            python-version: '3.7'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython wheel setuptools

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.13.1

      - name: Install PyArmor
        run: pip install pyarmor

      - name: Obfuscate Python code
        run: pyarmor obfuscate --recursive --output miksi_ai_sdk_obfuscated miksi_ai_sdk

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install Cython && python setup.py build_ext --inplace
          CIBW_BUILD_VERBOSITY: 1  # Increase verbosity to diagnose issues

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload-to-pypi:
    needs: build-and-upload
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Download all build artifacts
        uses: actions/download-artifact@v2
        with:
          path: wheelhouse  # Extracting directly in 'wheelhouse' directory

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
