name: Build and Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install cython
          pip install pyinstaller

      - name: Build binary distribution
        run: |
          mkdir -p miksi_ai_sdk/dist
          pyinstaller --onefile --distpath miksi_ai_sdk/dist miksi_ai_sdk/*.py

      - name: List files in dist directory
        run: |
          ls -la miksi_ai_sdk/dist

      - name: Publish to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_KEY }}
          distributions: "miksi_ai_sdk/dist/*"
          skip-existing: true
