name: Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build wheels
        run: |
          docker run --rm -v $(pwd):/mnt python:3.9 /bin/bash -c "cd /mnt && python setup.py bdist_wheel"

      - name: Upload wheels to PyPI
        uses: pypa/gh-action-pypi-publish@unstable/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: dist/
