name: Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Adjust Python version as needed

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel  # Ensure wheel package is installed
          pip install langchain sqlalchemy pymysql langchain_openai openai

      - name: Build wheels
        run: |
          python setup.py bdist_wheel
          if [[ "$RUNNER_OS" == "Linux" ]]; then auditwheel repair dist/*.whl; fi

      - name: Upload wheels to PyPI
        uses: pypa/gh-action-pypi-publish@unstable/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: wheelhouse/
