name: Build and Publish to PyPI

on:
  push:
    branches: 
      - main  # Ensure this matches your main development branch's name.
  pull_request:  # This lets you build on PRs without publishing.

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust the Python version as needed.

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython setuptools wheel

    - name: Build Wheels with cibuildwheel
    uses: pypa/cibuildwheel@v2.16.2
    with:
      output-dir: 'wheelhouse'
    env:
      CIBW_BEFORE_BUILD: 'pip install Cython && pip install .[tests]


  publish:
    needs: build_wheels
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}