name: Build and Publish Python Package

on:
  push:
    

jobs:

  build-and-publish:
    name: Build and publish Python package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine cibuildwheel==2.16.2

    - name: Build binary wheels
      env:
        CIBW_BEFORE_BUILD: pip install Cython
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - name: Publish distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload --skip-existing wheelhouse/*.whl