name: Build and Publish

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Feel free to specify a more precise version.
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BEFORE_BUILD: python -m pip install Cython
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_to_pypi:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Match this version with the one used for building wheels.
      - name: Install twine
        run: python -m pip install twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine check dist/*
          twine upload dist/*