name: Build and Publish Python Package

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython twine cibuildwheel
      
      - name: Build Wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      
      - name: List Wheel Contents
        run: |
          for whl in wheelhouse/*.whl; do
            unzip -l "$whl"
          done
      
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main'
        run: |
          python -m twine upload wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

env:
  CIBW_BEFORE_BUILD: "pip install setuptools wheel cython"
  CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*
  # Ensure we only build wheels for the platforms we are interested in
  CIBW_SKIP: "*-win32 *-manylinux_i686"
  CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w {dest_dir} {wheel}"
