name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you want to use

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          # Specify the platforms you want to build for
          platforms: "windows"
          # Other cibuildwheel configuration options...
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
