name: Build and Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: quay.io/pypa/manylinux2010_x86_64:latest
        options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make build script executable
        run: chmod +x build_wheels.sh
      
      - name: Set up Docker container
        run: docker info
        
      - name: Build manylinux wheels
        run: docker run --rm -e PLAT=manylinux2010_x86_64 -v `pwd`:/github/workspace quay.io/pypa/manylinux2010_x86_64 /github/workspace/build_wheels.sh
        
      - name: Upload wheels to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist