name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # You can adjust the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython wheel  # Ensure wheel package is installed
          pip install langchain sqlalchemy pymysql langchain_openai openai

      - name: Build wheels
        run: python setup.py sdist bdist_wheel

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl
